/* ============================================================
   Lista de procedimientos para el autocompletado.
   La misma para todas las cosmiatras y para los doctores.

   Para cambiarla, edita este archivo y guarda. No hay que tocar
   nada mas: la app la lee sola al abrir.
   ============================================================ */

var PROCEDIMIENTOS = [
  "Emsculpt",
  "Emsculpt Neo",
  "Exilis Exion",
  "Exilis",
  "Uniform",
  "Emtone",
  "MR",
  "Radiofrecuencia",
  "RF",
  "4RF",
  "6RF",
  "12RF",
  "CO2",
  "Carboxiterapia",
  "Criolipólisis",
  "Ondas de choque",
  "Vanquish",
  "LPG",
  "Tratamiento corporal",
  "Drenaje linfático",
  "Drenaje manual",
  "Masajes",
  "Campana LED",
  "Terapia de estrías",
  "Visbody",
  "Evaluación corporal",
  "Evaluación cosmiátrica",
  "Medidas",
  "Peso",
  "Emface",
  "HIFU",
  "Ultraformer",
  "MPT",
  "Emfusion facial",
  "Jet Peel",
  "RF facial",
  "RF ojeras",
  "Peeling",
  "Mascarilla mandélico",
  "Mascarilla Youthel",
  "Mascarilla de alginato",
  "Limpieza de rostro",
  "Limpieza profunda",
  "Extracción de puntos negros",
  "Desmaquillado",
  "Lámpara LED",
  "Exilis facial",
  "Exilis periocular",
  "Exilis cuello",
  "Exilis contorno",
  "Exion facial",
  "Exion vaginal",
  "Exosomas",
  "Plasma",
  "Extracción de sangre",
  "Centrifugado de sangre",
  "Peptonas",
  "Vitamina C",
  "Pack de Vida",
  "Jalupro",
  "Jalupro Young",
  "Jalupro Classic",
  "Jalupro HMW",
  "Lanluma X",
  "Microagujas",
  "Morpheus",
  "Botox",
  "Enzimas",
  "Infiltración",
  "Mounjaro",
  "Cicavit",
  "Aquazol",
  "Clobetasol + gel",
  "Resorcina",
  "Agua termal",
  "Protector solar",
  "Anestesia",
  "Crema anestésica",
  "Carboxiterapia capilar",
  "Láser capilar",
  "Limpieza de cuero cabelludo",
  "Dutasteride",
  "Pink Intimate",
  "Láser MTone",
  "Láser Pico",
  "Láser CO2",
  "Láser cauterización",
  "Láser tatuaje",
  "Láser manchas",
  "Láser verrugas y pápulas",
  "Láser cicatriz",
  "Láser estrías",
  "Dysport",
  "Fotos",
  "Cuadro comparativo",
  "Calentamiento",
  "Agendamiento",
  "Receta",
  "Explicación de receta",
  "Explicación de kit",
  "Entrega de kit",
  "Explicación de tratamiento",
  "Control de mitad",
  "Control final",
  "Fill",
  "Colocación de parches",
  "Retiro de parches",
  "Retiro de crema anestésica",
  "Retiro de mascarilla",
  "Retiro de manípulos",
  "Cambio de manípulos",
  "Cambio de equipo",
  "Limpieza de cabina",
  "Limpieza de camilla",
  "Limpieza de paciente",
  "Capacitación",
  "M-School",
  "Grabaciones",
  "Venta de paquete"
];

/* Estos se hacen por zona del cuerpo. Al escribir el nombre y un
   espacio, la app sugiere las zonas: "Emsculpt " -> "Emsculpt abdomen".
   No hay que escribirlas todas aqui: se arman solas. */
var POR_ZONA = [
  "Emsculpt",
  "Emsculpt Neo",
  "Exilis Exion",
  "Exilis",
  "Uniform",
  "Emtone",
  "MR",
  "Radiofrecuencia",
  "RF",
  "4RF",
  "6RF",
  "12RF",
  "CO2",
  "Carboxiterapia",
  "Criolipólisis",
  "Ondas de choque",
  "Vanquish",
  "LPG",
  "Tratamiento corporal",
  "Drenaje linfático",
  "Drenaje manual",
  "Masajes",
  "Campana LED",
  "Terapia de estrías"
];

var ZONAS = [
  "abdomen",
  "cintura",
  "glúteos",
  "banana",
  "entrepierna",
  "brazos",
  "pierna delantera",
  "pantorrillas",
  "cartuchera",
  "laterales",
  "espalda"
];
